DROP TABLE IF EXISTS tbl_EMPLOYEES;

CREATE TABLE tbl_EMPLOYEES{
    id INT  AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR (250) NOT NULL
    las_name VARCHAR (250 NOT NULL)
    email VARCHAR (250) DEFAULT NULL
};
